main.o: runge_kutta.h runge_kutta.cxx pendulum.h pendulum.cxx anharmonics.h anharmonics.cxx hw2.cxx
	g++ runge_kutta.h runge_kutta.cxx pendulum.h pendulum.cxx anharmonics.h anharmonics.cxx hw2.cxx -o main.o `root-config --cflags --glibs`
